name: Sync Yahoo Fantasy Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Function
        run: |
          curl -X POST "https://fantasy-football-tracker.netlify.app/.netlify/functions/sync-yahoo" \
            -H "Content-Type: application/json"